#!/system/bin/sh
# blockads - Blocks ads in Browser and Apps

mount -o remount,rw -t yaffs2 /dev/block/mtdblock4 /system
busybox mv /system/xbin/hostsblock /system/etc/hosts
busybox cp /system/etc/hosts /system/xbin
busybox mv /system/xbin/hosts /system/xbin/hostsblock
mount -o remount,ro -t yaffs2 /dev/block/mtdblock4 /system
sync
echo 'Ads have been blocked'
echo 'Succulent Desire by: Woodyman'

