#!/system/bin/sh
# cpuinfo - Shows CPU Information
mount -o remount,rw -t yaffs2 /dev/block/mtdblock4 /system
cat /proc/cpuinfo
mount -o remount,ro -t yaffs2 /dev/block/mtdblock4 /system
sync

echo 'See what Woodyman can do.!'
echo 'He just made your droid super-human'
