#!/system/bin/sh
# showads - Will allow advertisements to show in Browser and Apps

mount -o remount,rw -t yaffs2 /dev/block/mtdblock4 /system
busybox mv /system/xbin/hostsshow /system/etc/hosts
busybox cp /system/etc/hosts /system/xbin
busybox mv /system/xbin/hosts /system/xbin/hostsshow
mount -o remount,ro -t yaffs2 /dev/block/mtdblock4 /system
sync
echo 'Ads are now permitted to display'
echo 'Succulent Desire by: Woodyman'

