#!/system/bin/sh
# soundon - Enables camera and video recording sounds

mount -o remount,rw -t yaffs2 /dev/block/mtdblock4 /system
busybox mv /system/media/audio/ui/camera_click.bak /system/media/audio/ui/camera_click.ogg
busybox mv /system/media/audio/ui/VideoRecord.bak /system/media/audio/ui/VideoRecord.ogg
mount -o remount,ro -t yaffs2 /dev/block/mtdblock4 /system
sync
echo 'Camera & Video Recording Sounds Enabled'
echo 'Succulent Desire by: Woodyman'
